//! Emitting the handles struct and trait implementations for a parameter set.

use proc_macro2::TokenStream;
use quote::{format_ident, quote, quote_spanned};
use syn::{spanned::Spanned, DeriveInput, Expr, Ident};

use super::{
    attrs::{range_bounds, SetAttrs},
    enum_set::{Variant, VariantShape},
    Field,
};

pub(crate) fn generate(input: &DeriveInput, set: &SetAttrs, fields: &[Field]) -> TokenStream {
    let values = &input.ident;
    let handles = handles_ident(input, set);
    let visibility = &input.vis;

    // A `skip`ped field has no parameter and no handle, so it takes part in nothing below except
    // the snapshot, where it is filled in from `Default`.
    let declared: Vec<&Field> = fields.iter().filter(|f| f.is_declared()).collect();

    let handle_fields = declared.iter().map(|field| {
        let ident = field.ident;
        let doc = handle_field_doc(field);
        let handle = handle_type(field);
        quote_spanned! { field.span() =>
            #[doc = #doc]
            pub #ident: #handle
        }
    });

    let handles_doc = format!(
        "Live parameter handles for [`{values}`].\n\n\
         Generated by `#[derive(ParameterSet)]`. Each field holds the handle for the \
         corresponding parameter of [`{values}`], and dropping this struct undeclares all of \
         them unless the node was asked to retain them.",
    );

    let namespace = set
        .namespace
        .as_ref()
        .map(|ns| ns.value())
        .unwrap_or_default();

    let defaults = destructure_defaults(set, &declared);
    let has_own_default = set.default.is_some();
    let field_inits = declared
        .iter()
        .map(|field| declare_field(field, has_own_default));
    let snapshot_fields = fields.iter().map(snapshot_field);

    // Four items are emitted: the handles struct, `ParameterSet` to declare the parameters and
    // `ParameterSetHandles` to read them back, and `DeclareField` so that a set can be a field of
    // another set, which is what makes nesting work without any annotation.
    quote! {
        #[doc = #handles_doc]
        #visibility struct #handles {
            #(#handle_fields,)*
        }

        impl ::rclrs::ParameterSet for #values {
            type Handles = #handles;

            const NAMESPACE: &'static str = #namespace;

            fn declare(
                node: &::rclrs::NodeState,
                prefix: &str,
                default: ::core::option::Option<Self>,
            ) -> ::core::result::Result<Self::Handles, ::rclrs::ParameterSetError> {
                #defaults
                ::core::result::Result::Ok(#handles {
                    #(#field_inits,)*
                })
            }
        }

        impl ::rclrs::ParameterSetHandles for #handles {
            type Values = #values;

            fn snapshot(&self) -> #values {
                #values {
                    #(#snapshot_fields,)*
                }
            }
        }

        impl ::rclrs::DeclareField<::rclrs::Writable> for #values {
            type Value = Self;
            type Handle = #handles;
            type Range = ();

            fn declare(
                node: &::rclrs::NodeState,
                name: &str,
                spec: ::rclrs::FieldSpec<Self::Value, Self::Range>,
            ) -> ::core::result::Result<Self::Handle, ::rclrs::ParameterSetError> {
                <Self as ::rclrs::ParameterSet>::declare(node, name, spec.default)
            }

            fn snapshot(handle: &Self::Handle) -> Self {
                <#handles as ::rclrs::ParameterSetHandles>::snapshot(handle)
            }

            fn into_default(self) -> ::core::option::Option<Self::Value> {
                ::core::option::Option::Some(self)
            }
        }

        impl ::rclrs::DeclareFlattened<::rclrs::Writable> for #values {}
    }
}

/// The handle a field's declaration produces.
fn handle_type(field: &Field) -> TokenStream {
    if field.is_converted() {
        let handle = format_ident!("{}", converted_kind(field).0);
        let value = field.converted_value_ty();
        return quote!(::rclrs::#handle<#value>);
    }
    let ty = field.ty;
    let mode = field.mode();
    quote!(<#ty as ::rclrs::DeclareField<#mode>>::Handle)
}

/// The handle a converted field produces and the entry point that declares it.
///
/// One classification rather than two, because the two have to agree for the generated code to
/// compile and nothing else would enforce that.
fn converted_kind(field: &Field) -> (&'static str, &'static str) {
    if field.is_optional() {
        ("OptionalParameter", "declare_converted_optional")
    } else if field.attrs.read_only.is_some() {
        ("ReadOnlyParameter", "declare_converted_read_only")
    } else {
        ("MandatoryParameter", "declare_converted")
    }
}

/// Which of the converted declaration entry points a field needs.
fn converted_declare_fn(field: &Field) -> Ident {
    format_ident!("{}", converted_kind(field).1)
}

/// The name of the generated handles struct.
fn handles_ident(input: &DeriveInput, set: &SetAttrs) -> Ident {
    set.handles
        .clone()
        .unwrap_or_else(|| format_ident!("{}Params", input.ident, span = input.ident.span()))
}

fn handle_field_doc(field: &Field) -> String {
    let description = field.attrs.description_text();
    let name = &field.name;
    if description.is_empty() {
        format!("Handle for the `{name}` parameter.")
    } else {
        format!("Handle for the `{name}` parameter.\n\n{description}")
    }
}

/// Which value a set of per-field default bindings was taken from.
///
/// The two are kept apart because they do not carry the same authority. See [`default_value`].
#[derive(Clone, Copy)]
pub(crate) enum DefaultSource {
    /// The value passed in for this one instance of the set, from a parent field's `default` or
    /// from the caller of `declare_parameters`.
    Supplied,
    /// The set's own `#[parameters(default = ...)]`.
    Own,
}

/// Takes each available default value apart so that every field can be given its own.
///
/// A supplied value and the set's own `#[parameters(default = ...)]` are destructured separately,
/// because a field's `#[param(default = ...)]` sits between them in precedence.
fn destructure_defaults(set: &SetAttrs, declared: &[&Field]) -> TokenStream {
    // With no declared fields there is nothing to hand a default to. The expression is still
    // emitted, so that a mistake in it is still reported, and dropped so that it does not warn.
    if declared.is_empty() {
        let own = set.default.as_ref().map(|expr| quote!(let _ = #expr;));
        return quote! {
            let _ = default;
            #own
        };
    }

    // Each source is taken apart in one `match`, giving every field its own binding. Mapping over
    // the value once per field would move the same `Option` more than once, and cloning it instead
    // would need a `Clone` bound that a values struct does not have to satisfy.
    let supplied = destructure_one(quote!(default), DefaultSource::Supplied, declared);
    let own = set.default.as_ref().map(|expr| {
        // Evaluated whether or not it ends up being used, since which fields fall through to it
        // is not known until each one has been resolved.
        destructure_one(
            quote!(::core::option::Option::Some(#expr)),
            DefaultSource::Own,
            declared,
        )
    });

    quote! {
        #supplied
        #own
    }
}

/// Destructures one `Option<Self>` into a binding per field.
fn destructure_one(value: TokenStream, source: DefaultSource, declared: &[&Field]) -> TokenStream {
    let bindings = declared.iter().map(|field| default_binding(field, source));
    let somes = declared.iter().map(|field| {
        let ident = field.ident;
        quote!(::core::option::Option::Some(__d.#ident))
    });
    let nones = declared
        .iter()
        .map(|_| quote!(::core::option::Option::None));

    quote! {
        let (#(#bindings,)*) = match #value {
            ::core::option::Option::Some(__d) => (#(#somes,)*),
            ::core::option::Option::None => (#(#nones,)*),
        };
    }
}

fn default_binding(field: &Field, source: DefaultSource) -> Ident {
    match source {
        DefaultSource::Supplied => format_ident!("__supplied_{}", field.ident),
        DefaultSource::Own => format_ident!("__own_{}", field.ident),
    }
}

/// The initializer for one field of the handles struct.
fn declare_field(field: &Field, has_own_default: bool) -> TokenStream {
    let ident = field.ident;
    let ty = field.ty;
    let mode = field.mode();
    let spec = field_spec(field, has_own_default);
    let span = field.span();

    let name = &field.name;
    let declare = if let Some(conversion) = &field.attrs.convert {
        // A converted field cannot go through `DeclareField`: its type may belong to another
        // crate, so no implementation for it could exist. The conversion travels alongside the
        // spec instead.
        let declare_fn = converted_declare_fn(field);
        quote_spanned! { conversion.span() =>
            ::rclrs::#declare_fn(
                node,
                &::rclrs::join_parameter_name(prefix, #name),
                #spec,
                #conversion,
            )?
        }
    } else if field.attrs.flatten.is_some() {
        quote_spanned! { span =>
            <#ty as ::rclrs::DeclareFlattened<#mode>>::declare_flattened(node, prefix, #spec)?
        }
    } else {
        quote_spanned! { span =>
            <#ty as ::rclrs::DeclareField<#mode>>::declare(
                node,
                &::rclrs::join_parameter_name(prefix, #name),
                #spec,
            )?
        }
    };

    match &field.attrs.on_change {
        // `on_change` is registered on the handle rather than passed in the spec, so that its
        // signature is the handle's own: `fn(&T)` for a mandatory parameter, `fn(Option<&T>)`
        // for an optional one. Getting it wrong then points at the real signature.
        Some(callback) => quote_spanned! { callback.span() =>
            #ident: {
                let __handle = #declare;
                __handle.on_change(#callback);
                __handle
            }
        },
        None => quote_spanned! { span => #ident: #declare },
    }
}

/// The `FieldSpec` for one field.
fn field_spec(field: &Field, has_own_default: bool) -> TokenStream {
    let attrs = &field.attrs;
    let default = default_value(field, has_own_default);
    let description = attrs.description_text();
    let constraints = attrs
        .constraints
        .as_ref()
        .map(|c| c.value())
        .unwrap_or_default();
    let range = range_value(field);
    let ignore_override = attrs.ignore_override.is_some();
    let discard = attrs.discard_mismatching_prior_value.is_some();
    let validate = boxed_callback(attrs.validate.as_ref());
    let discriminate = boxed_callback(attrs.discriminate.as_ref());

    quote! {
        ::rclrs::FieldSpec {
            default: #default,
            description: #description,
            constraints: #constraints,
            range: #range,
            ignore_override: #ignore_override,
            discard_mismatching_prior_value: #discard,
            validate: #validate,
            discriminate: #discriminate,
        }
    }
}

/// The default value expression for a field, from whichever source has the most authority.
///
/// Three of them, in order:
///
/// 1. A value supplied for this instance of the set, from a parent field's `default`. It
///    configures one particular use of the set, so it beats what the set says about itself, and
///    it is what lets a parent configure a nested set it did not write.
/// 2. The field's own `#[param(default = ...)]`.
/// 3. The set's `#[parameters(default = ...)]`. Both this and the field attribute describe the
///    type in general, so the more specific of the two wins, which is the field's.
///
/// Literals in the field attribute get the conversion they obviously need: a string literal for a
/// `String` field, and an array literal for a `Vec<String>` field, are what an application would
/// want to write.
fn default_value(field: &Field, has_own: bool) -> TokenStream {
    let from = |source| {
        let ty = field.ty;
        let mode = field.mode();
        let binding = default_binding(field, source);
        if field.is_converted() {
            // The value is already what the parameter takes, so an optional field's default is
            // itself and any other field's is present by construction.
            return if field.is_optional() {
                quote!(::core::option::Option::and_then(#binding, ::core::convert::identity))
            } else {
                quote!(::core::option::Option::and_then(
                    #binding,
                    ::core::option::Option::Some
                ))
            };
        }
        quote! {
            ::core::option::Option::and_then(
                #binding,
                <#ty as ::rclrs::DeclareField<#mode>>::into_default,
            )
        }
    };

    let mut value = from(DefaultSource::Supplied);
    if let Some(expr) = &field.attrs.default {
        let literal = convert_literal(expr);
        value = quote_spanned! { expr.span() =>
            ::core::option::Option::or(#value, ::core::option::Option::Some(#literal))
        };
    }
    if has_own {
        let own = from(DefaultSource::Own);
        value = quote!(::core::option::Option::or(#value, #own));
    }
    value
}

/// Adds the conversion a literal default needs to become the field's type.
///
/// Only string literals and the elements of an array literal are treated this way. Converting
/// arbitrary expressions with `Into::into` would make integer literal defaults ambiguous, since
/// several `From` implementations can apply.
fn convert_literal(expr: &Expr) -> TokenStream {
    match expr {
        // `default = "robot"` for a String, PathBuf or Arc<str> field.
        Expr::Lit(syn::ExprLit {
            lit: syn::Lit::Str(_),
            ..
        }) => quote_spanned! { expr.span() => ::core::convert::Into::into(#expr) },
        // `default = ["left", "right"]` for a Vec<String> field. Each element is converted on its
        // own terms, so a numeric array keeps its literals untouched and infers their type from
        // the field: `[8080, 9090]` for a Vec<u16> would not compile through `Into`, since an
        // integer literal defaults to i32 and a u16 cannot be made from one.
        Expr::Array(array) => {
            let elements = array.elems.iter().map(convert_literal);
            quote_spanned! { expr.span() =>
                ::core::iter::IntoIterator::into_iter([#(#elements),*]).collect()
            }
        }
        _ => quote!(#expr),
    }
}

fn range_value(field: &Field) -> TokenStream {
    let attrs = &field.attrs;
    let Some(range) = &attrs.range else {
        return quote!(::core::default::Default::default());
    };

    // The range is handed over as written wherever it can be, so the builder's own conversions
    // decide what a range may be and the answer is the same in a set as anywhere else. A step is
    // part of no Rust range, so it is added afterwards.
    if !field.is_converted() {
        let converted = quote_spanned!(range.span() => ::core::convert::Into::into(#range));
        return match &attrs.step {
            // Named before the step is added, because a method call cannot drive the inference
            // that decides which range the conversion produces.
            Some(step) => {
                let ty = field.ty;
                let mode = field.mode();
                quote_spanned! { step.span() =>
                    {
                        let range: <#ty as ::rclrs::DeclareField<#mode>>::Range = #converted;
                        range.with_step(#step)
                    }
                }
            }
            None => converted,
        };
    }

    // Already reported by `check_field`. Emit something that compiles so that the rest of the
    // errors are reported too.
    let Ok(bounds) = range_bounds(range) else {
        return quote!(::core::default::Default::default());
    };

    let lower = optional(bounds.lower);
    let upper = optional(bounds.upper);
    let step = optional(attrs.step.as_ref());

    let literal = quote_spanned! { range.span() =>
        ::rclrs::ParameterRange {
            lower: #lower,
            upper: #upper,
            step: #step,
        }
    };
    if field.is_converted() {
        // A converted field's spec carries the erased form, in the terms the conversion stores
        // the value in, because there is no type to name a `Range` on.
        return quote_spanned!(range.span() => ::core::convert::Into::into(#literal));
    }
    literal
}

fn optional(expr: Option<&Expr>) -> TokenStream {
    match expr {
        Some(expr) => quote!(::core::option::Option::Some(#expr)),
        None => quote!(::core::option::Option::None),
    }
}

fn boxed_callback(expr: Option<&Expr>) -> TokenStream {
    match expr {
        Some(expr) => quote_spanned! { expr.span() =>
            ::core::option::Option::Some(::std::boxed::Box::new(#expr))
        },
        None => quote!(::core::option::Option::None),
    }
}

/// How one field of the values struct is read back out of the handles.
fn snapshot_field(field: &Field) -> TokenStream {
    let ident = field.ident;

    if !field.is_declared() {
        return quote_spanned! { field.span() =>
            #ident: ::core::default::Default::default()
        };
    }

    if field.is_converted() {
        // The handle already yields the field's type, `T` or `Option<T>` as declared.
        return quote_spanned! { field.span() =>
            #ident: self.#ident.get()
        };
    }

    let ty = field.ty;
    let mode = field.mode();

    quote_spanned! { field.span() =>
        #ident: <#ty as ::rclrs::DeclareField<#mode>>::snapshot(&self.#ident)
    }
}

// ---------------------------------------------------------------------------------------------
// Enum sets
// ---------------------------------------------------------------------------------------------

/// Generates the handles and trait implementations for an enum parameter set.
///
/// Two types are generated: a struct holding the tag parameter's handle and the variant's
/// handles, and an enum mirroring the user's for the latter. The tag has to be kept somewhere so
/// that the parameter stays declared, and an enum cannot have a field common to all its variants.
pub(crate) fn generate_enum(
    input: &DeriveInput,
    set: &SetAttrs,
    tag: &str,
    variants: &[Variant],
) -> TokenStream {
    let values = &input.ident;
    let handles = handles_ident(input, set);
    let variant_handles = format_ident!("{}VariantParams", values, span = values.span());
    let visibility = &input.vis;

    let handle_variants = variants.iter().map(|variant| {
        let ident = variant.ident;
        
        match &variant.shape {
            VariantShape::Fields(fields) => {
                let handles = fields.iter().map(|field| {
                    let field_ident = field.ident;
                    let ty = field.ty;
                    let mode = field.mode();
                    let doc = handle_field_doc(field);
                    
                    quote_spanned! { field.span() =>
                        #[doc = #doc]
                        #field_ident: <#ty as ::rclrs::DeclareField<#mode>>::Handle
                    }
                });

                quote!(#ident { #(#handles,)* })
            }
            VariantShape::Delegate(ty) => {
                quote!(#ident(<#ty as ::rclrs::DeclareField<::rclrs::Writable>>::Handle))
            }
            VariantShape::Unit => quote!(#ident),
        }
    });

    let tag_values: Vec<&str> = variants.iter().map(|v| v.tag.as_str()).collect();
    let constraints = format!("one of: {}", tag_values.join(", "));
    let unknown_tag = format!(
        "unknown {values} '{{}}', expected one of: {}",
        tag_values.join(", ")
    );
    let tag_description = set_doc(input);

    // Which tag value a supplied default value corresponds to.
    let tag_defaults = variants.iter().map(|variant| {
        let ident = variant.ident;
        let tag = &variant.tag;
        
        let pattern = match &variant.shape {
            VariantShape::Fields(_) => quote!(#values::#ident { .. }),
            VariantShape::Delegate(_) => quote!(#values::#ident(..)),
            VariantShape::Unit => quote!(#values::#ident),
        };
        
        quote! {
            ::core::option::Option::Some(#pattern) => {
                ::core::option::Option::Some(::std::string::String::from(#tag))
            }
        }
    });

    let declare_arms = variants.iter().map(|variant| {
        let ident = variant.ident;
        let tag = &variant.tag;
        
        let body = match &variant.shape {
            VariantShape::Fields(fields) => {
                let declared: Vec<&Field> = fields.iter().filter(|f| f.is_declared()).collect();
                let defaults = destructure_variant_defaults(values, ident, &declared);
                let inits = declared.iter().map(|field| declare_field(field, false));
                
                quote! {{
                    #defaults
                    #variant_handles::#ident { #(#inits,)* }
                }}
            }
            VariantShape::Delegate(ty) => quote! {{
                let __inner_default = match __default {
                    ::core::option::Option::Some(#values::#ident(__inner)) => {
                        ::core::option::Option::Some(__inner)
                    }
                    _ => ::core::option::Option::None,
                };
                
                // Declared under this set's own namespace: the variant is identified by the tag,
                // so it does not add a namespace of its own.
                #variant_handles::#ident(
                    <#ty as ::rclrs::DeclareField<::rclrs::Writable>>::declare(
                        node,
                        prefix,
                        ::rclrs::FieldSpec {
                            default: __inner_default,
                            ..::core::default::Default::default()
                        },
                    )?,
                )
            }},
            VariantShape::Unit => quote!(#variant_handles::#ident),
        };

        quote!(#tag => #body)
    });

    let snapshot_arms = variants.iter().map(|variant| {
        let ident = variant.ident;
        
        match &variant.shape {
            VariantShape::Fields(fields) => {
                let declared: Vec<&Field> = fields.iter().filter(|f| f.is_declared()).collect();
                let bindings = declared.iter().map(|field| field.ident);
                
                let reads = fields.iter().map(|field| {
                    let field_ident = field.ident;
                    
                    if !field.is_declared() {
                        return quote!(#field_ident: ::core::default::Default::default());
                    }
                    
                    let ty = field.ty;
                    let mode = field.mode();
                    
                    quote!(#field_ident: <#ty as ::rclrs::DeclareField<#mode>>::snapshot(#field_ident))
                });

                quote! {
                    #variant_handles::#ident { #(#bindings,)* } => #values::#ident { #(#reads,)* }
                }
            }
            VariantShape::Delegate(ty) => quote! {
                #variant_handles::#ident(__inner) => #values::#ident(
                    <#ty as ::rclrs::DeclareField<::rclrs::Writable>>::snapshot(__inner),
                )
            },
            VariantShape::Unit => quote!(#variant_handles::#ident => #values::#ident),
        }
    });

    let namespace = set
        .namespace
        .as_ref()
        .map(|ns| ns.value())
        .unwrap_or_default();

    let default_source = match &set.default {
        Some(expr) => quote! {
            let __default = ::core::option::Option::or_else(
                default,
                || ::core::option::Option::Some(#expr),
            );
        },
        None => quote!(let __default = default;),
    };

    let handles_doc = format!(
        "Live parameter handles for [`{values}`].\n\n\
         Generated by `#[derive(ParameterSet)]`. `variant` holds the handles for whichever \
         variant the `{tag}` parameter selected.",
    );

    let variant_handles_doc = format!(
        "Live parameter handles for the variants of [`{values}`], generated by \
         `#[derive(ParameterSet)]`.",
    );

    quote! {
        #[doc = #handles_doc]
        #visibility struct #handles {
            #[doc = "Handles for the variant that is in use."]
            pub variant: #variant_handles,
            // Holds the tag parameter open for as long as these handles live. It is read-only,
            // so there is nothing to expose beyond the value it resolved to.
            tag: ::rclrs::ReadOnlyParameter<::std::string::String>,
        }

        impl #handles {
            #[doc = "The value of the tag parameter that selected this variant."]
            pub fn tag(&self) -> ::std::string::String {
                ::rclrs::ReadOnlyParameter::get(&self.tag)
            }
        }

        #[doc = #variant_handles_doc]
        #visibility enum #variant_handles {
            #(#handle_variants,)*
        }

        impl ::rclrs::ParameterSet for #values {
            type Handles = #handles;

            const NAMESPACE: &'static str = #namespace;

            fn declare(
                node: &::rclrs::NodeState,
                prefix: &str,
                default: ::core::option::Option<Self>,
            ) -> ::core::result::Result<Self::Handles, ::rclrs::ParameterSetError> {
                #default_source

                // The tag is declared first, because what else there is to declare depends on it.
                let __tag_name = ::rclrs::join_parameter_name(prefix, #tag);
                let __tag_default = match &__default {
                    #(#tag_defaults,)*
                    ::core::option::Option::None => ::core::option::Option::None,
                };
                let __tag = <::std::string::String as ::rclrs::DeclareField<::rclrs::ReadOnly>>::declare(
                    node,
                    &__tag_name,
                    ::rclrs::FieldSpec {
                        default: __tag_default,
                        description: #tag_description,
                        constraints: #constraints,
                        validate: ::core::option::Option::Some(::std::boxed::Box::new(
                            |__value: &::std::string::String| {
                                match ::core::convert::AsRef::<str>::as_ref(__value) {
                                    #(#tag_values)|* => ::core::result::Result::Ok(()),
                                    __other => ::core::result::Result::Err(
                                        ::std::format!(#unknown_tag, __other),
                                    ),
                                }
                            },
                        )),
                        ..::core::default::Default::default()
                    },
                )?;

                let __variant = match ::core::convert::AsRef::<str>::as_ref(
                    &::rclrs::ReadOnlyParameter::get(&__tag),
                ) {
                    #(#declare_arms,)*
                    // Unreachable: the validate callback above rejects anything else, which fails
                    // the declaration of the tag before this point.
                    __other => ::core::unreachable!(
                        "the tag parameter accepted a value that is not a known variant: {}",
                        __other,
                    ),
                };

                ::core::result::Result::Ok(#handles {
                    variant: __variant,
                    tag: __tag,
                })
            }
        }

        impl ::rclrs::ParameterSetHandles for #handles {
            type Values = #values;

            fn snapshot(&self) -> #values {
                match &self.variant {
                    #(#snapshot_arms,)*
                }
            }
        }

        impl ::rclrs::DeclareField<::rclrs::Writable> for #values {
            type Value = Self;
            type Handle = #handles;
            type Range = ();

            fn declare(
                node: &::rclrs::NodeState,
                name: &str,
                spec: ::rclrs::FieldSpec<Self::Value, Self::Range>,
            ) -> ::core::result::Result<Self::Handle, ::rclrs::ParameterSetError> {
                <Self as ::rclrs::ParameterSet>::declare(node, name, spec.default)
            }

            fn snapshot(handle: &Self::Handle) -> Self {
                <#handles as ::rclrs::ParameterSetHandles>::snapshot(handle)
            }

            fn into_default(self) -> ::core::option::Option<Self::Value> {
                ::core::option::Option::Some(self)
            }
        }

        impl ::rclrs::DeclareFlattened<::rclrs::Writable> for #values {}
    }
}

/// Takes a variant's default value apart, so that each of its fields can be given a default.
fn destructure_variant_defaults(
    values: &Ident,
    variant: &Ident,
    declared: &[&Field],
) -> TokenStream {
    if declared.is_empty() {
        return quote!(let _ = &__default;);
    }
    
    let bindings = declared.iter().map(|field| {
        let binding = default_binding(field, DefaultSource::Supplied);
        quote!(#binding)
    });
    
    let field_idents = declared.iter().map(|field| field.ident);
    
    let somes = declared
        .iter()
        .map(|field| {
            let ident = field.ident;
            quote!(::core::option::Option::Some(#ident))
        })
        .collect::<Vec<_>>();
    
    let nones = declared
        .iter()
        .map(|_| quote!(::core::option::Option::None));

    quote! {
        let (#(#bindings,)*) = match __default {
            ::core::option::Option::Some(#values::#variant { #(#field_idents,)* .. }) => {
                (#(#somes,)*)
            }
            _ => (#(#nones,)*),
        };
    }
}

/// The doc comment on the type itself, used to describe the tag parameter.
fn set_doc(input: &DeriveInput) -> String {
    input
        .attrs
        .iter()
        .filter_map(|attr| {
            if !attr.path().is_ident("doc") {
                return None;
            }
            
            let syn::Meta::NameValue(name_value) = &attr.meta else {
                return None;
            };
            
            let Expr::Lit(syn::ExprLit {
                lit: syn::Lit::Str(text),
                ..
            }) = &name_value.value
            else {
                return None;
            };
            
            let line = text.value();
            
            Some(line.strip_prefix(' ').unwrap_or(&line).to_string())
        })
        .collect::<Vec<_>>()
        .join("\n")
}
