//! Emitting the handles struct and trait implementations for a parameter set.

use proc_macro2::TokenStream;
use quote::{format_ident, quote, quote_spanned};
use syn::{spanned::Spanned, DeriveInput, Expr, Ident};

use super::{
    attrs::{range_bounds, FieldAttrs, SetAttrs},
    Field,
};

pub(crate) fn generate(input: &DeriveInput, set: &SetAttrs, fields: &[Field]) -> TokenStream {
    let values = &input.ident;
    let handles = handles_ident(input, set);
    let visibility = &input.vis;

    // A `skip`ped field has no parameter and no handle, so it takes part in nothing below except
    // the snapshot, where it is filled in from `Default`.
    let declared: Vec<&Field> = fields.iter().filter(|f| f.is_declared()).collect();

    let handle_fields = declared.iter().map(|field| {
        let ident = field.ident;
        let ty = field.ty;
        let mode = field.mode();
        let doc = handle_field_doc(field);
        quote_spanned! { field.span() =>
            #[doc = #doc]
            pub #ident: <#ty as ::rclrs::DeclareField<#mode>>::Handle
        }
    });

    let handles_doc = format!(
        "Live parameter handles for [`{values}`].\n\n\
         Generated by `#[derive(ParameterSet)]`. Each field holds the handle for the \
         corresponding parameter of [`{values}`], and dropping this struct undeclares all of \
         them unless the node was asked to retain them.",
    );

    let namespace = set
        .namespace
        .as_ref()
        .map(|ns| ns.value())
        .unwrap_or_default();

    let defaults = destructure_defaults(set, &declared);
    let has_own_default = set.default.is_some();
    let field_inits = declared
        .iter()
        .map(|field| declare_field(field, has_own_default));
    let snapshot_fields = fields.iter().map(snapshot_field);

    // Four items are emitted: the handles struct, `ParameterSet` to declare the parameters and
    // `ParameterSetHandles` to read them back, and `DeclareField` so that a set can be a field of
    // another set, which is what makes nesting work without any annotation.
    quote! {
        #[doc = #handles_doc]
        #visibility struct #handles {
            #(#handle_fields,)*
        }

        impl ::rclrs::ParameterSet for #values {
            type Handles = #handles;

            const NAMESPACE: &'static str = #namespace;

            fn declare(
                node: &::rclrs::NodeState,
                prefix: &str,
                default: ::core::option::Option<Self>,
            ) -> ::core::result::Result<Self::Handles, ::rclrs::ParameterSetError> {
                #defaults
                ::core::result::Result::Ok(#handles {
                    #(#field_inits,)*
                })
            }
        }

        impl ::rclrs::ParameterSetHandles for #handles {
            type Values = #values;

            fn snapshot(&self) -> #values {
                #values {
                    #(#snapshot_fields,)*
                }
            }
        }

        impl ::rclrs::DeclareField<::rclrs::Writable> for #values {
            type Value = Self;
            type Handle = #handles;
            type Range = ();

            fn declare(
                node: &::rclrs::NodeState,
                name: &str,
                spec: ::rclrs::FieldSpec<Self::Value, Self::Range>,
            ) -> ::core::result::Result<Self::Handle, ::rclrs::ParameterSetError> {
                <Self as ::rclrs::ParameterSet>::declare(node, name, spec.default)
            }

            fn snapshot(handle: &Self::Handle) -> Self {
                <#handles as ::rclrs::ParameterSetHandles>::snapshot(handle)
            }

            fn into_default(self) -> ::core::option::Option<Self::Value> {
                ::core::option::Option::Some(self)
            }
        }

        impl ::rclrs::DeclareFlattened<::rclrs::Writable> for #values {}
    }
}

/// The name of the generated handles struct.
fn handles_ident(input: &DeriveInput, set: &SetAttrs) -> Ident {
    set.handles
        .clone()
        .unwrap_or_else(|| format_ident!("{}Params", input.ident, span = input.ident.span()))
}

fn handle_field_doc(field: &Field) -> String {
    let description = field.attrs.description_text();
    let name = &field.name;
    if description.is_empty() {
        format!("Handle for the `{name}` parameter.")
    } else {
        format!("Handle for the `{name}` parameter.\n\n{description}")
    }
}

/// Which value a set of per-field default bindings was taken from.
///
/// The two are kept apart because they do not carry the same authority. See [`default_value`].
#[derive(Clone, Copy)]
pub(crate) enum DefaultSource {
    /// The value passed in for this one instance of the set, from a parent field's `default` or
    /// from the caller of `declare_parameters`.
    Supplied,
    /// The set's own `#[parameters(default = ...)]`.
    Own,
}

/// Takes each available default value apart so that every field can be given its own.
///
/// A supplied value and the set's own `#[parameters(default = ...)]` are destructured separately,
/// because a field's `#[param(default = ...)]` sits between them in precedence.
fn destructure_defaults(set: &SetAttrs, declared: &[&Field]) -> TokenStream {
    // With no declared fields there is nothing to hand a default to. The expression is still
    // emitted, so that a mistake in it is still reported, and dropped so that it does not warn.
    if declared.is_empty() {
        let own = set.default.as_ref().map(|expr| quote!(let _ = #expr;));
        return quote! {
            let _ = default;
            #own
        };
    }

    // Each source is taken apart in one `match`, giving every field its own binding. Mapping over
    // the value once per field would move the same `Option` more than once, and cloning it instead
    // would need a `Clone` bound that a values struct does not have to satisfy.
    let supplied = destructure_one(quote!(default), DefaultSource::Supplied, declared);
    let own = set.default.as_ref().map(|expr| {
        // Evaluated whether or not it ends up being used, since which fields fall through to it
        // is not known until each one has been resolved.
        destructure_one(
            quote!(::core::option::Option::Some(#expr)),
            DefaultSource::Own,
            declared,
        )
    });

    quote! {
        #supplied
        #own
    }
}

/// Destructures one `Option<Self>` into a binding per field.
fn destructure_one(value: TokenStream, source: DefaultSource, declared: &[&Field]) -> TokenStream {
    let bindings = declared.iter().map(|field| default_binding(field, source));
    let somes = declared.iter().map(|field| {
        let ident = field.ident;
        quote!(::core::option::Option::Some(__d.#ident))
    });
    let nones = declared
        .iter()
        .map(|_| quote!(::core::option::Option::None));

    quote! {
        let (#(#bindings,)*) = match #value {
            ::core::option::Option::Some(__d) => (#(#somes,)*),
            ::core::option::Option::None => (#(#nones,)*),
        };
    }
}

fn default_binding(field: &Field, source: DefaultSource) -> Ident {
    match source {
        DefaultSource::Supplied => format_ident!("__supplied_{}", field.ident),
        DefaultSource::Own => format_ident!("__own_{}", field.ident),
    }
}

/// The initializer for one field of the handles struct.
fn declare_field(field: &Field, has_own_default: bool) -> TokenStream {
    let ident = field.ident;
    let ty = field.ty;
    let mode = field.mode();
    let spec = field_spec(field, has_own_default);
    let span = field.span();

    let declare = if field.attrs.flatten.is_some() {
        quote_spanned! { span =>
            <#ty as ::rclrs::DeclareFlattened<#mode>>::declare_flattened(node, prefix, #spec)?
        }
    } else {
        let name = &field.name;
        quote_spanned! { span =>
            <#ty as ::rclrs::DeclareField<#mode>>::declare(
                node,
                &::rclrs::join_parameter_name(prefix, #name),
                #spec,
            )?
        }
    };

    match &field.attrs.on_change {
        // `on_change` is registered on the handle rather than passed in the spec, so that its
        // signature is the handle's own: `fn(&T)` for a mandatory parameter, `fn(Option<&T>)`
        // for an optional one. Getting it wrong then points at the real signature.
        Some(callback) => quote_spanned! { callback.span() =>
            #ident: {
                let __handle = #declare;
                __handle.on_change(#callback);
                __handle
            }
        },
        None => quote_spanned! { span => #ident: #declare },
    }
}

/// The `FieldSpec` for one field.
fn field_spec(field: &Field, has_own_default: bool) -> TokenStream {
    let attrs = &field.attrs;
    let default = default_value(field, has_own_default);
    let description = attrs.description_text();
    let constraints = attrs
        .constraints
        .as_ref()
        .map(|c| c.value())
        .unwrap_or_default();
    let range = range_value(attrs);
    let ignore_override = attrs.ignore_override.is_some();
    let discard = attrs.discard_mismatching_prior_value.is_some();
    let validate = boxed_callback(attrs.validate.as_ref());
    let discriminate = boxed_callback(attrs.discriminate.as_ref());

    quote! {
        ::rclrs::FieldSpec {
            default: #default,
            description: #description,
            constraints: #constraints,
            range: #range,
            ignore_override: #ignore_override,
            discard_mismatching_prior_value: #discard,
            validate: #validate,
            discriminate: #discriminate,
        }
    }
}

/// The default value expression for a field, from whichever source has the most authority.
///
/// Three of them, in order:
///
/// 1. A value supplied for this instance of the set, from a parent field's `default`. It
///    configures one particular use of the set, so it beats what the set says about itself, and
///    it is what lets a parent configure a nested set it did not write.
/// 2. The field's own `#[param(default = ...)]`.
/// 3. The set's `#[parameters(default = ...)]`. Both this and the field attribute describe the
///    type in general, so the more specific of the two wins, which is the field's.
///
/// Literals in the field attribute get the conversion they obviously need: a string literal for a
/// `String` field, and an array literal for a `Vec<String>` field, are what an application would
/// want to write.
fn default_value(field: &Field, has_own: bool) -> TokenStream {
    let from = |source| {
        let ty = field.ty;
        let mode = field.mode();
        let binding = default_binding(field, source);
        quote! {
            ::core::option::Option::and_then(
                #binding,
                <#ty as ::rclrs::DeclareField<#mode>>::into_default,
            )
        }
    };

    let mut value = from(DefaultSource::Supplied);
    if let Some(expr) = &field.attrs.default {
        let literal = convert_literal(expr);
        value = quote_spanned! { expr.span() =>
            ::core::option::Option::or(#value, ::core::option::Option::Some(#literal))
        };
    }
    if has_own {
        let own = from(DefaultSource::Own);
        value = quote!(::core::option::Option::or(#value, #own));
    }
    value
}

/// Adds the conversion a literal default needs to become the field's type.
///
/// Only string literals and the elements of an array literal are treated this way. Converting
/// arbitrary expressions with `Into::into` would make integer literal defaults ambiguous, since
/// several `From` implementations can apply.
fn convert_literal(expr: &Expr) -> TokenStream {
    match expr {
        // `default = "robot"` for a String, PathBuf or Arc<str> field.
        Expr::Lit(syn::ExprLit {
            lit: syn::Lit::Str(_),
            ..
        }) => quote_spanned! { expr.span() => ::core::convert::Into::into(#expr) },
        // `default = ["left", "right"]` for a Vec<String> field. Each element is converted on its
        // own terms, so a numeric array keeps its literals untouched and infers their type from
        // the field: `[8080, 9090]` for a Vec<u16> would not compile through `Into`, since an
        // integer literal defaults to i32 and a u16 cannot be made from one.
        Expr::Array(array) => {
            let elements = array.elems.iter().map(convert_literal);
            quote_spanned! { expr.span() =>
                ::core::iter::IntoIterator::into_iter([#(#elements),*]).collect()
            }
        }
        _ => quote!(#expr),
    }
}

fn range_value(attrs: &FieldAttrs) -> TokenStream {
    let Some(range) = &attrs.range else {
        return quote!(::core::default::Default::default());
    };

    // Already reported by `check_field`. Emit something that compiles so that the rest of the
    // errors are reported too.
    let Ok(bounds) = range_bounds(range) else {
        return quote!(::core::default::Default::default());
    };

    let lower = optional(bounds.lower);
    let upper = optional(bounds.upper);
    let step = optional(attrs.step.as_ref());

    quote_spanned! { range.span() =>
        ::rclrs::ParameterRange {
            lower: #lower,
            upper: #upper,
            step: #step,
        }
    }
}

fn optional(expr: Option<&Expr>) -> TokenStream {
    match expr {
        Some(expr) => quote!(::core::option::Option::Some(#expr)),
        None => quote!(::core::option::Option::None),
    }
}

fn boxed_callback(expr: Option<&Expr>) -> TokenStream {
    match expr {
        Some(expr) => quote_spanned! { expr.span() =>
            ::core::option::Option::Some(::std::boxed::Box::new(#expr))
        },
        None => quote!(::core::option::Option::None),
    }
}

/// How one field of the values struct is read back out of the handles.
fn snapshot_field(field: &Field) -> TokenStream {
    let ident = field.ident;

    if !field.is_declared() {
        return quote_spanned! { field.span() =>
            #ident: ::core::default::Default::default()
        };
    }

    let ty = field.ty;
    let mode = field.mode();

    quote_spanned! { field.span() =>
        #ident: <#ty as ::rclrs::DeclareField<#mode>>::snapshot(&self.#ident)
    }
}
