bool bool_value true
byte byte_value
char char_value
float32 float32_value 1.125
float64 float64_value
int8 int8_value -5
uint8 uint8_value 23
int16 int16_value
uint16 uint16_value
int32 int32_value
uint32 uint32_value
int64 int64_value
uint64 uint64_value
string string_value
string string_value_with_default 'default'
#string<=5[3] fixed_length_string_value
#string<=5[<=10] upper_bound_string_value
string unbound_string_value
