bool bool_value false
byte byte_value 1
char char_value 1
float32 float32_value 1.23
float64 float64_value
int8 int8_value -5
uint16[2] two_uint16_value [5, 23]
int32[<=3] up_to_three_int32_values
int32[<=3] up_to_three_int32_values_with_default_values [5, 23]
uint64[] unbounded_uint64_values

#string[2] two_string_value ['foo', 'bar']
string[<=3] up_to_three_string_values
string[] unbounded_string_values

Empty empty
Empty[2] two_empty
Empty[] unbounded_empty

Nested nested
Nested[2] two_nested
Nested[<=3] up_to_three_nested
Nested[] unbounded_nested
