# A list of parameters of which to get the descriptor.
string[] names

---

# A list of the descriptors of all parameters requested in the same order
# as they were requested.
# This list has the same length as the list of parameters requested.
ParameterDescriptor[] descriptors
