# A list of parameter names.
# TODO(wjwwood): link to parameter naming rules.
string[] names

---

# List of types which is the same length and order as the provided names.
# Type enum defined in ParameterType.msg
# ParameterType.PARAMETER_NOT_SET indicates that the parameter is not currently set.
uint8[] types
