uint64 DEPTH_RECURSIVE=0

# The list of parameter prefixes to query.
string[] prefixes
# Relative depth from given prefixes to return.
# Use DEPTH_RECURSIVE to get the recursive parameters and prefixes for each prefix.
uint64 depth

---

ListParametersResult result
